### ISSUE TITLE
How to use synonym filter?

### ISSUE THREAD

**Issue by cassianotartari** [ruflin/Elastica#695]
Hello!

   I don't know what version of elastica, foselasticabundle e elasticsearch I was using before but in another project that I've done when I want to use the `synonym` filter I did like this:

``` yml
fos_elastica:
    indexes:
        my_index:
            client: default
            settings:
                index:
                    analysis:
                        filter:
                            synonym:
                                type: synonym
                                synonyms_path : "%kernel.root_dir%/../app/config/synonym.txt"
```

But now it returns:

```
$ php app/console fos:elastica:populate
Resetting my_index

  [Elastica\Exception\ResponseException]                                                                                                                        
  IndexCreationException[[my_index] failed to create index]; nested: FailedToResolveConfigException[Failed to resolve config path [/var/www/mine/app/../a  
  pp/config/synonym.txt], tried file path [/var/www/mine/app/../app/config/synonym.txt], path file [/etc/elasticsearch/var/www/mine/app/../app/config/synonym.  
  txt], and classpath];                                                                                                                                                                                                                                                                                                         
fos:elastica:populate [--index[="..."]] [--type[="..."]] [--no-reset] [--offset="..."] [--sleep="..."] [--batch-size="..."] [--ignore-errors]
```

I've tried with:

``` yml
synonyms_path: "%kernel.root_dir%/config/synonym.txt"
```

Without success too.

I'm working with last version of elasticsearch and

```
"friendsofsymfony/elastica-bundle": "3.0.*@alpha",
```

with Symfony 2.3.20

Any ideas?
